import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { client } from '@/storyblok/client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // const navigation = await client.query({
  //   query: navigationQuery
  // })

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navigation {...storyblokDataToNavigation(navigation)} /> */}
        {children}
      </body>
    </html>
  )
}