import { storyblokSdk } from '@/storyblok/client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { storyblokDataToNavigation } from '@/components/layout/navigation/dataMapper'
import { Navigation } from '@/components/layout/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const navigation = await storyblokSdk?.Navigation()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation {...storyblokDataToNavigation(navigation)} />
        {children}
      </body>
    </html>
  )
}